language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cargo test --verbose --package blot-lib --features blot-lib/common_json golden
