[package]
name = "blot-lib"
version = "0.1.0"
authors = ["Arnau Siches <asiches@gmail.com>"]

[lib]
name = "blot"
path = "src/lib.rs"

[dependencies]
sha-1 = "0.7"
sha2 = "0.7"
sha3 = "0.7"
blake2 = "0.7"
digest = "0.7"
hex = "0.3"
serde_json = "1.0"
serde = "1.0"
serde_derive = "1.0"
itertools = "0.7.8"
ansi_term = "0.11"

[features]
default = []
common_json = []
